name: Ansible Deployment to AWS

# Trigger the workflow on pushes to the 'main' branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest  # You can change this to `amazonlinux2`, `fedora-latest`, or `self-hosted` if needed.

    steps:
    # Step 1: Checkout the code from the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up Python and install dependencies
    - name: Set up Python and Install Dependencies
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    # Step 3: Install Ansible and other necessary Python packages
    - name: Install Ansible
      run: |
        python -m pip install --upgrade pip
        pip install ansible boto3

      # Step 4: Configure AWS credentials from GitHub secrets
    - name: Set up AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.ACESS_KEY }}
        aws-secret-access-key: ${{ secrets.SECRETE_KEY}}
        aws-region: ${{ secrets.REGION }}

    
    # Step 5: Set up inventory directory and file
    - name: Set up inventory file
      run: |
        mkdir -p inventory  # Create the inventory directory if it doesn't exist
        echo "[ec2_instances]" > inventory/aws_ec2.ini
        echo "ec2-34.205.73.136.compute-1.amazonaws.com ansible_ssh_private_key_file=/home/ec2-user/yes.pem ansible_user=ec2-user" >> inventory/aws_ec2.ini  # Updated inventory configuration
        
    # Step 6: Run the Ansible Playbook
    - name: Run Ansible Playbook
      run: |
        # Ensure the PEM file has correct permissions
        chmod 600 /home/ec2-user/yes.pem  # Make sure the PEM file is secure
 
        
        # Run the Ansible playbook
        ansible-playbook -i inventory/aws_ec2.ini playbooks/deploy.yml
