name: Ansible Deployment to AWS

# Trigger the workflow on pushes to the 'main' branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest  # You can change this to amazonlinux2, fedora-latest, or self-hosted if needed.

    steps:
    # Step 1: Checkout the code from the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up Python and install dependencies
    - name: Set up Python and Install Dependencies
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    # Step 3: Install Ansible and other necessary Python packages
    - name: Install Ansible
      run: |
        python -m pip install --upgrade pip
        pip install ansible boto3

    # Step 4: Configure AWS credentials from GitHub secrets
    - name: Set up AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.ACESS_KEY}}
        aws-secret-access-key: ${{ secrets.SECRETE_KEY }}
        aws-region: ${{ secrets.REGION }}

    # Step 5: Set up PEM file from GitHub Secrets
    - name: Set up PEM file from GitHub Secrets
      run: |
        echo "${{ secrets.PEM_FILE }}" > /home/runner/yes.pem
        chmod 600 /home/runner/yes.pem

    # Step 6: Add EC2 instance to known hosts (Prevent SSH verification issues)
    - name: Add EC2 instance to known hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan ec2-34-205-73-136.compute-1.amazonaws.com >> ~/.ssh/known_hosts

    # Step 7: Set up inventory file for Ansible
    - name: Set up inventory file
      run: |
        mkdir -p inventory  # Create the inventory directory if it doesn't exist
        echo "[ec2_instances]" > inventory/aws_ec2.ini
        echo "34.205.73.136 ansible_ssh_private_key_file=/home/runner/yes.pem ansible_user=ec2-user" >> inventory/aws_ec2.ini

    # Step 8: Run the Ansible Playbook
    - name: Run Ansible Playbook
      run: |
        ansible-playbook -i inventory/aws_ec2.ini playbooks/deploy.yml
